import { Directory, DirectoryType, DirectoryCategory } from "./types";

// Extract parenthetical notes from names like "Product Hunt (the GOAT)"
function parseName(raw: string): { name: string; notes: string | null } {
  const match = raw.match(/^(.*?)\s*\(([^)]+)\)\s*$/);
  if (!match) return { name: raw.trim(), notes: null };
  return { name: match[1].trim(), notes: match[2].trim() };
}

function inferType(raw: string): DirectoryType {
  const lower = raw.toLowerCase();
  if (
    lower.includes("expensive") ||
    lower.includes("paid") ||
    lower.includes("$") ||
    lower.includes("sell")
  )
    return "paid";
  if (lower.includes("freemium")) return "freemium";
  return "free";
}

interface RawEntry {
  num: number;
  name: string;
  url: string;
  da: number | null;
  dofollow?: boolean;
}

function transform(entries: RawEntry[], prefix: string, category: DirectoryCategory): Directory[] {
  return entries.map((e) => {
    const { name, notes } = parseName(e.name);
    return {
      id: `${prefix}-${e.num}`,
      num: e.num,
      name,
      url: e.url,
      da: e.da ?? null,
      dr: e.da ?? null,
      type: inferType(e.name),
      dofollow: e.dofollow ?? true,
      notes,
      category,
    };
  });
}

const rawSaasDirectories: RawEntry[] = [
  { num: 1, name: "LinkedIn Groups", url: "https://www.linkedin.com/groups", da: 99, dofollow: false },
  { num: 2, name: "Reddit Niche Subreddits", url: "https://medium.com/stackademic/how-to-use-reddit-for-saas-marketing-2b0b64fef1e3", da: 95, dofollow: false },
  { num: 3, name: "TrustPilot", url: "https://www.trustpilot.com", da: 94 },
  { num: 4, name: "Better Business Bureau", url: "https://www.bbb.org", da: 91 },
  { num: 5, name: "Product Hunt", url: "https://www.producthunt.com", da: 91 },
  { num: 6, name: "DEV Community", url: "https://dev.to", da: 90 },
  { num: 7, name: "Hacker News", url: "https://news.ycombinator.com", da: 89 },
  { num: 8, name: "HackerNoon", url: "https://hackernoon.com", da: 88 },
  { num: 9, name: "TrustRadius", url: "http://trustradius.com", da: 84 },
  { num: 10, name: "Dang AI (paid)", url: "https://dang.ai", da: 81 },
  { num: 12, name: "Fazier.com", url: "https://fazier.com", da: 80 },
  { num: 13, name: "Indiehackers", url: "https://www.indiehackers.com", da: 80 },
  { num: 14, name: "AlternativeTo", url: "http://alternativeto.net", da: 79 },
  { num: 15, name: "Twelve.Tools", url: "https://twelve.tools", da: 79 },
  { num: 16, name: "Turbo0 (high-quality backlink)", url: "https://turbo0.com", da: 79 },
  { num: 17, name: "EU-Startups Database", url: "https://www.eu-startups.com/directory", da: 77 },
  { num: 18, name: "There's an AI for that!", url: "https://theresanaiforthat.com", da: 77 },
  { num: 19, name: "SaaSHub", url: "https://www.saashub.com", da: 76 },
  { num: 20, name: "ToolPilot AI", url: "https://www.toolpilot.ai", da: 76 },
  { num: 21, name: "Peerlist (high traffic)", url: "https://peerlist.io/r4fken/signup", da: 76 },
  { num: 22, name: "Startup Fame", url: "https://startupfa.me", da: 76 },
  { num: 23, name: "Findly", url: "https://findly.tools", da: 76 },
  { num: 24, name: "Starter Story", url: "https://www.starterstory.com/share", da: 75 },
  { num: 25, name: "Crunchbase", url: "https://crunchbase.com", da: 75 },
  { num: 26, name: "Show Me Best AI", url: "https://www.showmebest.ai", da: 75 },
  { num: 27, name: "Uneed (the next ProductHunt, must-have)", url: "https://www.uneed.best?atp=linkto&ref=linkto", da: 74 },
  { num: 28, name: "SaaSWorthy", url: "https://www.saasworthy.com", da: 74 },
  { num: 29, name: "Betalist", url: "https://betalist.com", da: 74 },
  { num: 30, name: "Alternative Me", url: "https://alternative.me", da: 73 },
  { num: 31, name: "Startup Inspire", url: "http://startupinspire.com/startups", da: 72 },
  { num: 32, name: "AllTopStartups", url: "https://alltopstartups.com", da: 72 },
  { num: 33, name: "PeerPush (high traffic)", url: "https://peerpush.net?atp=rafv", da: 72 },
  { num: 34, name: "Crowd Reviews", url: "http://crowdreviews.com", da: 71 },
  { num: 35, name: "AllMyFaves", url: "https://allmyfaves.com", da: 71 },
  { num: 36, name: "SideProjectors", url: "https://www.sideprojectors.com", da: 70 },
  { num: 37, name: "Toolfame", url: "https://toolfame.com", da: 69 },
  { num: 38, name: "OpenTools", url: "https://opentools.ai", da: 68 },
  { num: 39, name: "Spotsaas", url: "https://www.spotsaas.com", da: 67 },
  { num: 40, name: "Good AI Tools", url: "https://goodaitools.com", da: 67 },
  { num: 41, name: "Indiepa.ge (solid do-follow backlinks instantly)", url: "https://indiepa.ge", da: 67 },
  { num: 42, name: "Growth Hackers", url: "https://growthhackers.com", da: 66 },
  { num: 43, name: "Startup Stash (expensive backlink)", url: "https://startupstash.com/add-listing", da: 66 },
  { num: 44, name: "SimilarLabs", url: "https://similarlabs.com", da: 65 },
  { num: 45, name: "TrustMRR (read fine print first)", url: "https://trustmrr.com", da: 65 },
  { num: 46, name: "Foundr", url: "https://foundr.com", da: 64 },
  { num: 47, name: "Submissions Web Directory", url: "https://www.submissionwebdirectory.com", da: 63 },
  { num: 48, name: "FoundrList", url: "https://foundrlist.com/?a=linkto&ref=linkto", da: 63 },
  { num: 49, name: "NoCode Tech", url: "https://www.nocode.tech/tools", da: 62 },
  { num: 50, name: "SimilarSites", url: "http://www.similarsites.com", da: 62 },
  { num: 51, name: "EBool", url: "https://www.ebool.com", da: 61 },
  { num: 52, name: "SoMuch", url: "https://somuch.com", da: 61 },
  { num: 53, name: "Libhunt", url: "https://www.libhunt.com", da: 61 },
  { num: 54, name: "AppSumo (sell)", url: "https://sell.appsumo.com", da: 61 },
  { num: 55, name: "PitchWall (free with 30 day wait)", url: "https://pitchwall.co", da: 60 },
  { num: 56, name: "Indie Deals", url: "https://indie.deals", da: 60 },
  { num: 57, name: "AI Tool Net", url: "https://www.aitoolnet.com", da: 59 },
  { num: 58, name: "Devhunt", url: "https://devhunt.org", da: 59 },
  { num: 59, name: "ToolFinder", url: "https://toolfinder.co", da: 59 },
  { num: 60, name: "SaaS Genius", url: "https://www.saasgenius.com/free-listing", da: 57 },
  { num: 61, name: "StartupsLab", url: "https://startupslab.site", da: 57 },
  { num: 62, name: "StarterBest", url: "https://starterbest.com", da: 57 },
  { num: 63, name: "MicroLaunch (expensive for what you get)", url: "https://microlaunch.net", da: 55 },
  { num: 64, name: "BstSky Tools (backlink badge required)", url: "https://bestsky.tools", da: 55 },
  { num: 65, name: "AppSumo", url: "https://appsumo.com", da: 54 },
  { num: 66, name: "SaaS AI Tools", url: "https://saasaitools.com", da: 54 },
  { num: 67, name: "Uno Directory", url: "https://uno.directory", da: 54 },
  { num: 68, name: "AI Top Tools", url: "https://aitoptools.com", da: 53 },
  { num: 69, name: "Yo.Directory", url: "https://yo.directory", da: 53 },
  { num: 70, name: "AIxploria", url: "https://www.aixploria.com/en", da: 52 },
  { num: 71, name: "Launching Next", url: "http://launchingnext.com", da: 51 },
  { num: 72, name: "SubmitMySaaS", url: "https://www.submitmysaas.com", da: 51 },
  { num: 73, name: "HuntScreen", url: "https://huntscreens.com", da: 51 },
  { num: 75, name: "OpenAlternative", url: "https://openalternative.co", da: 50 },
  { num: 76, name: "AI Tools Directory", url: "https://aitoolsdirectory.com", da: 49 },
  { num: 77, name: "500 Tools", url: "https://500.tools", da: 49 },
  { num: 78, name: "Huzzler", url: "https://huzzler.so?ref=R4FKEN&utm_source=linkto", da: 48 },
  { num: 79, name: "Coindoo", url: "https://coindoo.com/submit-press-release", da: 45 },
  { num: 80, name: "Workspaces", url: "http://workspaces.xyz/submit-a-workspace-workspaces", da: 45 },
  { num: 81, name: "BigStartups", url: "https://bigstartups.co", da: 45 },
  { num: 82, name: "Insidr AI Tools", url: "http://insidr.ai/submit-tools", da: 45 },
  { num: 83, name: "Fastlane Forum", url: "https://www.thefastlaneforum.com/community", da: 45 },
  { num: 84, name: "Trustiner", url: "https://trustiner.com", da: 45 },
  { num: 85, name: "AppaList", url: "https://appalist.com", da: 45 },
  { num: 86, name: "Toolfio", url: "https://toolfio.com", da: 45 },
  { num: 87, name: "TeachOnline", url: "https://teachonline.ca/tools-trends", da: 44 },
  { num: 88, name: "Similar Site Search", url: "http://similarsitesearch.com", da: 44 },
  { num: 90, name: "That App Show", url: "https://thatappshow.com", da: 44 },
  { num: 91, name: "Startup Beat", url: "https://startupbeat.com/get-featured", da: 44 },
  { num: 92, name: "Indie Hacker Projects", url: "https://indiehackerprojects.com", da: 44 },
  { num: 93, name: "VentureRadar", url: "http://ventureradar.com/add_company", da: 43 },
  { num: 94, name: "Thing Testing", url: "https://thingtesting.com/submit-brand", da: 43 },
  { num: 95, name: "Rundown AI", url: "https://www.rundown.ai", da: 43 },
  { num: 96, name: "Real World Beta Testing", url: "https://betatesting.com/beta-testing", da: 43 },
  { num: 97, name: "Ctrl Alt", url: "https://ctrlalt.cc", da: 43 },
  { num: 98, name: "AI Cyclopedia", url: "http://aicyclopedia.com", da: 41 },
  { num: 99, name: "StartupListing", url: "https://startuplist.ing", da: 41 },
  { num: 100, name: "Popular AI Tools", url: "https://popularaitools.ai/submit-a-tool", da: 40 },
  { num: 101, name: "Vic Trays", url: "https://victrays.com", da: 40 },
  { num: 102, name: "Startup Buffer", url: "https://startupbuffer.com", da: 40 },
  { num: 103, name: "Startupbase", url: "https://startupbase.io", da: 40 },
  { num: 104, name: "Foundr.ai", url: "https://foundr.ai", da: 40 },
  { num: 105, name: "IndieWall", url: "https://www.theindiewall.net", da: 40 },
  { num: 106, name: "AIGC 160", url: "https://aigc160.com", da: 40 },
  { num: 107, name: "Startup Guys", url: "http://startupguys.net/submit-startup", da: 39 },
  { num: 108, name: "fyple", url: "https://www.fyple.com", da: 39 },
  { num: 109, name: "SteemHunt", url: "https://steemhunt.com", da: 39 },
  { num: 110, name: "Startup Resources", url: "https://startupresources.io", da: 38 },
  { num: 111, name: "Tool Directory", url: "https://tooldirectory.ai", da: 38 },
  { num: 112, name: "Make.rs", url: "https://make.rs", da: 38 },
  { num: 113, name: "NoCodeList", url: "https://nocodelist.co", da: 38 },
  { num: 114, name: "Toolio.ai", url: "https://www.toolio.ai", da: 38 },
  { num: 115, name: "Rank Your AI", url: "https://rankyourai.com", da: 38 },
  { num: 116, name: "StartupTrusted", url: "https://startuptrusted.com", da: 38 },
  { num: 117, name: "TopAI.tools", url: "https://topai.tools", da: 37 },
  { num: 118, name: "Web Tools Weekly", url: "http://webtoolsweekly.com/submit", da: 37 },
  { num: 119, name: "Submit A Startup", url: "http://thetechpanda.com/submit-a-startup", da: 37 },
  { num: 120, name: "AllGPTs", url: "https://allgpts.co", da: 37 },
  { num: 121, name: "Saaspa.ge", url: "https://www.saaspa.ge", da: 37 },
  { num: 123, name: "Project Hatch", url: "https://www.projecthatch.co/your-story", da: 35 },
  { num: 124, name: "Startup Tile", url: "https://thestartuppitch.com/post-a-pitch", da: 35 },
  { num: 125, name: "Techboard", url: "https://techboard.com.au", da: 35 },
  { num: 126, name: "Bowora (previously Best of Web)", url: "https://bowora.com/?via=xrxo1fne&ref=linkto", da: 35 },
  { num: 127, name: "Wavel.io", url: "https://www.wavel.io", da: 35 },
  { num: 128, name: "New Startups", url: "https://www.new-startups.com", da: 34 },
  { num: 129, name: "Apps 400", url: "https://apps400.com", da: 34 },
  { num: 130, name: "10 Words", url: "https://10words.io", da: 34 },
  { num: 131, name: "1000 Tools", url: "https://1000.tools", da: 34 },
  { num: 132, name: "Top Similar Sites", url: "http://www.topsimilarsites.com/add.aspx", da: 34 },
  { num: 133, name: "Toolify", url: "https://www.toolify.ai", da: 34 },
  { num: 134, name: "Startup Tracker", url: "https://startuptracker.io", da: 34 },
  { num: 135, name: "Startups List", url: "https://www.startups-list.com", da: 34 },
  { num: 136, name: "Future Tools", url: "https://www.futuretools.io", da: 34 },
  { num: 137, name: "Startups.fm", url: "https://www.startups.fm", da: 34 },
  { num: 138, name: "Ask Your Android", url: "http://askyourandroid.com", da: 33 },
  { num: 139, name: "Cipinet", url: "https://www.cipinet.com/suggest.php", da: 33 },
  { num: 140, name: "AI Center", url: "https://aicenter.ai", da: 33 },
  { num: 142, name: "No Code Founders", url: "https://nocodefounders.com/startups", da: 33 },
  { num: 144, name: "FiveTaco", url: "http://fivetaco.com/submit", da: 33 },
  { num: 145, name: "OSS Gallery", url: "https://oss.gallery", da: 33 },
  { num: 146, name: "Appy Smarts", url: "https://www.appysmarts.com", da: 32 },
  { num: 147, name: "DoMore", url: "https://domore.ai", da: 32 },
  { num: 148, name: "ToolsAI", url: "https://toolsai.net", da: 32 },
  { num: 149, name: "The Hive Index", url: "https://thehiveindex.com/submit", da: 31 },
  { num: 150, name: "Top Software Companies", url: "https://www.topsoftwarecompanies.co", da: 31 },
  { num: 151, name: "Launched!", url: "https://launched.io", da: 31 },
  { num: 152, name: "App Review Central", url: "http://www.appreviewcentral.net/app-sub", da: 31 },
  { num: 153, name: "AI Valley", url: "https://aivalley.ai", da: 31 },
  { num: 154, name: "AI Top Tools", url: "https://www.toptools.ai", da: 31 },
  { num: 155, name: "AI TOOL GURU", url: "https://aitoolguru.com", da: 31 },
  { num: 156, name: "StartupSpotlight", url: "https://www.startupspotlight.co", da: 31 },
  { num: 157, name: "SaaSBaba", url: "https://saasbaba.com", da: 31 },
  { num: 158, name: "How Brands Are Built", url: "https://howbrandsarebuilt.com/submit", da: 30 },
  { num: 159, name: "Robingood", url: "https://tools.robingood.com", da: 30 },
  { num: 160, name: "Web App Rater", url: "https://webapprater.com", da: 30 },
  { num: 161, name: "AI Parabellum", url: "https://aiparabellum.com", da: 30 },
  { num: 162, name: "Techendo", url: "http://techendo.com/beta", da: 29 },
  { num: 163, name: "AllThingsAI", url: "https://allthingsai.com", da: 29 },
  { num: 165, name: "Toshilist", url: "https://www.toshilist.com", da: 28 },
  { num: 166, name: "9Sites.net", url: "https://www.9sites.net/addurl.php", da: 28 },
  { num: 167, name: "Startup Collections", url: "http://startupcollections.com", da: 28 },
  { num: 168, name: "Front-End Developers", url: "http://frontenddevelopers.org", da: 28 },
  { num: 169, name: "Trendy Startups", url: "http://trendystartups.com/register", da: 27 },
  { num: 170, name: "GPTDemo", url: "https://www.gptdemo.net", da: 27 },
  { num: 171, name: "Easy With AI", url: "https://easywithai.com", da: 27 },
  { num: 172, name: "Phygital.plus", url: "http://library.phygital.plus", da: 27 },
  { num: 173, name: "IndieHackerStacks", url: "http://indiehackerstacks.com", da: 27 },
  { num: 174, name: "Liiinks (insanely expensive)", url: "https://liiinks.net", da: 27 },
  { num: 175, name: "Ranccoon", url: "https://www.ranccoon.com/directory", da: 27 },
  { num: 176, name: "VibeCoders.bio", url: "https://vibecoders.bio", da: 26 },
  { num: 177, name: "AI Depot", url: "https://aidepot.co", da: 26 },
  { num: 178, name: "AwesomeIndie", url: "https://awesomeindie.com", da: 26 },
  { num: 179, name: "Indiedev.tools", url: "https://indiedev.tools", da: 26 },
  { num: 180, name: "Startup Roulette", url: "http://startuproulette.com", da: 25 },
  { num: 181, name: "AIScout", url: "https://aiscout.net", da: 25 },
  { num: 182, name: "The Startup Project", url: "https://www.startupproject.org", da: 25 },
  { num: 184, name: "Buffer apps", url: "https://www.bufferapps.com", da: 25 },
  { num: 185, name: "Owwly", url: "https://owwly.com", da: 25 },
  { num: 186, name: "Find My AI Tool", url: "https://findmyaitool.com", da: 24 },
  { num: 187, name: "Ai Tool Hunt", url: "https://www.aitoolhunt.com", da: 24 },
  { num: 188, name: "In Links We Trust", url: "https://inlinkswetrust.com", da: 24 },
  { num: 189, name: "Solo Launches", url: "https://sololaunches.com", da: 24 },
  { num: 190, name: "How to buy SaaS", url: "https://www.howtobuysaas.com", da: 23 },
  { num: 191, name: "Tiny Startups", url: "https://www.tinystartups.com", da: 23 },
  { num: 192, name: "Startup AI Tools", url: "https://www.startupaitools.com", da: 23 },
  { num: 194, name: "Discover Cloud", url: "https://www.discovercloud.com", da: 22 },
  { num: 195, name: "All Startups Info", url: "https://www.allstartups.info", da: 22 },
  { num: 197, name: "Alternatives.Co", url: "https://alternatives.co/software/ai-tools", da: 22 },
  { num: 198, name: "The Software Network", url: "http://www.thesoftwarenetwork.com", da: 21 },
  { num: 199, name: "The Startup Videos", url: "http://thestartupvideos.com", da: 21 },
  { num: 200, name: "Appoid", url: "https://appiod.com/submit-app-for-review", da: 21 },
  { num: 201, name: "Open Startup List", url: "https://openstartuplist.com", da: 21 },
  { num: 202, name: "Tech | Time", url: "https://webthat.io", da: 21 },
  { num: 203, name: "AI Tools Arena", url: "https://aitoolsarena.com", da: 21 },
  { num: 204, name: "SEOUL Startups", url: "https://www.seoulstartups.com", da: 21 },
  { num: 205, name: "Once.Tools", url: "https://once.tools", da: 21 },
  { num: 207, name: "Intribe", url: "https://www.intribe.co/launch-offer", da: 20 },
  { num: 208, name: "The Popular Apps", url: "http://thepopularapps.com/submit-app", da: 20 },
  { num: 209, name: "Maker Thrive", url: "https://makerthrive.com", da: 20 },
  { num: 210, name: "WebsiteHunt", url: "https://www.websitehunt.co", da: 20 },
  { num: 211, name: "Public APIs Dev", url: "https://publicapis.dev", da: 20 },
  { num: 213, name: "Tool Scout", url: "https://toolscout.ai", da: 20 },
  { num: 214, name: "FreeToolsLand", url: "https://freetoolsland.io", da: 20 },
  { num: 215, name: "HostedSoftware", url: "https://hostedsoftware.org", da: 20 },
  { num: 216, name: "Surges", url: "https://www.surges.co", da: 19 },
  { num: 217, name: "Open Future", url: "https://openfuture.ai", da: 19 },
  { num: 218, name: "SaaSCurate", url: "https://www.saascurate.com", da: 19 },
  { num: 219, name: "App Listo", url: "https://appslisto.com/submit-your-app", da: 18 },
  { num: 220, name: "AI Trends", url: "https://aitrendz.xyz", da: 18 },
  { num: 221, name: "FounderBeats", url: "https://founderbeats.com", da: 18 },
  { num: 222, name: "Nanai", url: "https://nanai.tools", da: 17 },
  { num: 223, name: "Startups.fyi", url: "https://www.startups.fyi", da: 17 },
  { num: 224, name: "Founders List", url: "https://founderslist.com", da: 17 },
  { num: 225, name: "AppsMirror", url: "http://www.appsmirror.com/submit-your-app-for-review", da: 17 },
  { num: 226, name: "AI Gems", url: "https://aigems.net", da: 17 },
  { num: 227, name: "Backlinks-List", url: "https://backlinks-list.com", da: 17 },
  { num: 228, name: "Startup Sea", url: "http://www.startupsea.com", da: 16 },
  { num: 229, name: "PayOnceApps", url: "https://payonceapps.com", da: 16 },
  { num: 230, name: "Human Or Not", url: "https://www.humanornot.co", da: 16 },
  { num: 231, name: "AI Wizard", url: "https://aiwizard.ai", da: 16 },
  { num: 232, name: "AI Tool Mate", url: "https://www.aitoolmate.com", da: 16 },
  { num: 233, name: "AppRater", url: "https://apprater.net", da: 16 },
  { num: 234, name: "Toolfolio", url: "https://toolfolio.io", da: 16 },
  { num: 235, name: "Directories.so", url: "https://directories.so", da: 16 },
  { num: 236, name: "Taalk", url: "https://taalk.com/submit-startup", da: 15 },
  { num: 237, name: "Venture Radar", url: "https://www.marsx.dev/ai-startups", da: 15 },
  { num: 238, name: "WeAreNoCode", url: "https://www.wearenocode.com", da: 15 },
  { num: 239, name: "AI product hub", url: "https://www.aiproducthub.com", da: 15 },
  { num: 240, name: "ToolBattles", url: "https://toolbattles.com", da: 15 },
  { num: 241, name: "SaasRefs", url: "https://www.saasrefs.com", da: 15 },
  { num: 242, name: "Uneed Directories (upcoming)", url: "https://uneed-directories.com/?atp=linkto&ref=linkto", da: 15 },
  { num: 243, name: "Easy Save AI", url: "https://easysaveai.com", da: 14 },
  { num: 244, name: "AI Tools guide", url: "https://aitoolsguide.com", da: 14 },
  { num: 245, name: "SaaS AI Tools (aitoolboard)", url: "https://aitoolboard.com", da: 14 },
  { num: 246, name: "Affonso", url: "https://affonso.io?atp=linkto", da: 14 },
  { num: 247, name: "Hackerspad", url: "https://hackerspad.net", da: 13 },
  { num: 248, name: "SaaS Directory", url: "http://saasdirectory.com", da: 13 },
  { num: 249, name: "Apps and Websites", url: "https://appsandwebsites.com", da: 13 },
  { num: 250, name: "AI directory", url: "https://www.aidirectory.org", da: 13 },
  { num: 251, name: "BroadWise", url: "https://broadwise.org", da: 13 },
  { num: 252, name: "DevTool", url: "https://devtool.io", da: 13 },
  { num: 255, name: "Joinly", url: "https://www.joinly.xyz", da: 12 },
  { num: 256, name: "Startup benchmarks", url: "https://www.startupbenchmarks.com", da: 12 },
  { num: 257, name: "Tool Salad", url: "https://toolsalad.com/submit", da: 12 },
  { num: 258, name: "Ready SaaS Go", url: "http://readysaasgo.com", da: 12 },
  { num: 259, name: "Fullstack AI", url: "https://fullstackai.co", da: 12 },
  { num: 260, name: "MadGenius", url: "https://madgenius.co", da: 12 },
  { num: 261, name: "Every AI", url: "https://every-ai.com", da: 12 },
  { num: 262, name: "Free AI tools directory", url: "https://free-ai-tools-directory.com", da: 12 },
  { num: 263, name: "AI Awesome", url: "https://www.aiawesome.com", da: 12 },
  { num: 264, name: "Top Free AI Tools", url: "https://topfreeaitools.com", da: 12 },
  { num: 265, name: "AffordHunt", url: "https://www.affordhunt.com", da: 12 },
  { num: 266, name: "ProdPapa", url: "https://www.prodpapa.com", da: 12 },
  { num: 267, name: "StartupTile", url: "https://startuptile.com", da: 11 },
  { num: 268, name: "Nextpedia", url: "https://www.nextpedia.io", da: 11 },
  { num: 269, name: "MarketerTools", url: "https://www.marketertools.co", da: 11 },
  { num: 270, name: "B2Saas", url: "https://b2saas.com", da: 11 },
  { num: 271, name: "MicroSaaSUp", url: "https://microsaasup.com", da: 11 },
  { num: 272, name: "Next Gen Tools", url: "https://nextgentools.me", da: 10 },
  { num: 273, name: "AI Tach", url: "https://aitach.com", da: 8 },
  { num: 274, name: "Extra List — flameitup.net", url: "https://flameitup.net/list", da: null },
  { num: 275, name: "Extra List — bestdirectories.org", url: "https://bestdirectories.org", da: null },
  { num: 277, name: "Extra List — launchdirectories.com", url: "https://launchdirectories.com", da: null },
  { num: 278, name: "Extra List — listingcat.com", url: "https://www.listingcat.com", da: null },
  { num: 279, name: "Extra List — github best-of-ai directories", url: "https://github.com/best-of-ai/ai-directories", da: null },
  // ── Added from resumefreepro submission history — DA/DR unknown ──
  { num: 281, name: "SpoT Startups", url: "https://spotstartups.com", da: 8 },
  { num: 282, name: "TryLaunch.ai", url: "https://trylaunch.ai", da: 18 },
  { num: 283, name: "SaaSlet", url: "https://saaslet.io", da: 1 },
  { num: 284, name: "Stackovery", url: "https://stackovery.com", da: 5 },
  { num: 285, name: "Show Me Your Site", url: "https://showmeyour.site", da: 9 },
  { num: 286, name: "Wired Business", url: "https://wired.business", da: 12 },
  { num: 287, name: "NewTool.site", url: "https://newtool.site", da: 18 },
  { num: 288, name: "Web Review", url: "https://web-review.com", da: 11 },
  { num: 289, name: "SaaSBison", url: "https://saasbison.com", da: 10 },
  { num: 290, name: "Neeed Directory", url: "https://neeed.directory", da: 37 },
  { num: 291, name: "Bro Directory", url: "https://bro.directory", da: 5 },
  { num: 292, name: "Launch.cab", url: "https://launch.cab", da: 9 },
  { num: 293, name: "ToolsFine", url: "https://toolsfine.com", da: 18 },
  { num: 294, name: "Hunt for Tools", url: "https://huntfortools.com", da: 47 },
  { num: 295, name: "AIToolFame", url: "https://aitoolfame.com", da: 21 },
  { num: 296, name: "AIX Collection", url: "https://aixcollection.com", da: 19 },
  { num: 297, name: "SubmitAITools", url: "https://submitaitools.org", da: 75 },
  { num: 298, name: "BetterLaunch", url: "https://betterlaunch.co", da: 11 },
  { num: 299, name: "Top Trend Tools", url: "https://toptrendtools.com", da: 44 },
  { num: 300, name: "SaaS Wheel", url: "https://saaswheel.com", da: 47 },
  { num: 301, name: "Tool Signal", url: "https://toolsignal.com", da: 42 },
  { num: 302, name: "SaaS Roots", url: "https://saasroots.com", da: 41 },
  { num: 303, name: "We Like Tools", url: "https://weliketools.com", da: 49 },
  { num: 304, name: "ProvenExpert", url: "https://www.provenexpert.com", da: 70 },
  { num: 305, name: "What Launched Today", url: "https://whatlaunched.today", da: 21 },
  { num: 306, name: "VibeRank", url: "https://viberank.dev", da: 9 },
  { num: 307, name: "AgentHunter", url: "https://www.agenthunter.io", da: 25 },
  { num: 308, name: "DeepLaunch", url: "https://deeplaunch.io", da: 16 },
  { num: 309, name: "Dironix", url: "https://dironix.com", da: 17 },
  { num: 310, name: "DevResources", url: "https://devresourc.es", da: 22 },
  { num: 311, name: "Shipit.buzz", url: "https://www.shipit.buzz", da: 10 },
];

const rawLaunchSites: RawEntry[] = [
  { num: 1, name: "Product Hunt (the GOAT)", url: "https://www.producthunt.com", da: 91 },
  { num: 2, name: "Hacker News", url: "https://news.ycombinator.com/news", da: 91 },
  { num: 3, name: "Fazier", url: "https://fazier.com", da: 81 },
  { num: 4, name: "Dang.ai (paid)", url: "https://dang.ai", da: 81 },
  { num: 5, name: "Indie Hackers", url: "https://www.indiehackers.com/products", da: 80 },
  { num: 6, name: "Turbo0 (high-value backlink)", url: "https://turbo0.com", da: 79 },
  { num: 7, name: "SaaSHub", url: "https://www.saashub.com", da: 77 },
  { num: 8, name: "There's An AI For That", url: "https://theresanaiforthat.com", da: 77 },
  { num: 9, name: "Peerlist (high traffic)", url: "https://peerlist.io/r4fken/signup", da: 76 },
  { num: 10, name: "Betalist", url: "https://betalist.com", da: 75 },
  { num: 11, name: "Uneed (the next ProductHunt, more popular every day)", url: "https://www.uneed.best?atp=linkto&ref=linkto", da: 74 },
  { num: 12, name: "LaunchIgniter", url: "https://launchigniter.com", da: 74 },
  { num: 13, name: "PeerPush (high traffic)", url: "https://peerpush.net?atp=rafv", da: 73 },
  { num: 14, name: "SaaS Adviser", url: "https://www.saasadviser.co", da: 72 },
  { num: 15, name: "AI Agents Directory", url: "https://aiagentsdirectory.com", da: 72 },
  { num: 16, name: "MagicBox.Tools", url: "https://magicbox.tools", da: 72 },
  { num: 17, name: "TinyLaunch", url: "https://www.tinylaun.ch", da: 71 },
  { num: 18, name: "OpenLaunch", url: "https://open-launch.com", da: 69 },
  { num: 19, name: "Aura++", url: "https://auraplusplus.com", da: 69 },
  { num: 20, name: "StartupFast", url: "https://www.startupfa.st", da: 68 },
  { num: 21, name: "FoundrList", url: "https://foundrlist.com/?a=linkto&ref=linkto", da: 63 },
  { num: 22, name: "PitchWall", url: "https://pitchwall.co", da: 62 },
  { num: 23, name: "Ufind.best", url: "https://ufind.best", da: 62 },
  { num: 24, name: "Dev Hunt", url: "https://devhunt.org", da: 61 },
  { num: 25, name: "SuperLaunch", url: "https://www.superlaun.ch", da: 60 },
  { num: 26, name: "MicroLaunch", url: "https://microlaunch.net", da: 59 },
  { num: 27, name: "AItoolnet", url: "https://www.aitoolnet.com", da: 57 },
  { num: 28, name: "Firsto", url: "https://firsto.co", da: 57 },
  { num: 29, name: "Uno.Directory", url: "https://uno.directory", da: 57 },
  { num: 30, name: "IndieHunt", url: "https://indiehunt.io", da: 55 },
  { num: 31, name: "SaaS AI Tools", url: "https://saasaitools.com", da: 54 },
  { num: 32, name: "WIP", url: "https://wip.co", da: 54 },
  { num: 33, name: "AI Top Tools", url: "https://aitoptools.com", da: 53 },
  { num: 34, name: "EarlyHunt", url: "https://earlyhunt.com", da: 52 },
  { num: 35, name: "LaunchingNext (free: 4 month delay; paid: $99)", url: "https://www.launchingnext.com/?n=115608&ref=linkto", da: 50 },
  { num: 36, name: "OpenHunts", url: "https://openhunts.com", da: 50 },
  { num: 37, name: "Shiny Launch", url: "https://shinylaunch.com", da: 50 },
  { num: 38, name: "Tiny Startups", url: "https://www.tinystartups.com", da: 49 },
  { num: 39, name: "CtrlAlt.cc", url: "https://ctrlalt.cc", da: 49 },
  { num: 40, name: "Huzzler", url: "https://huzzler.so?ref=R4FKEN&utm_source=linkto", da: 49 },
  { num: 41, name: "AI Tools", url: "https://aitools.fyi", da: 48 },
  { num: 42, name: "LaunchBoard", url: "https://www.launchboard.dev", da: 48 },
  { num: 43, name: "500 Tools", url: "https://500.tools", da: 48 },
  { num: 44, name: "LaunchItX", url: "https://launchitx.com", da: 48 },
  { num: 45, name: "IdeaKiln", url: "https://ideakiln.com", da: 48 },
  { num: 46, name: "SoloPush", url: "https://solopush.com", da: 47 },
  { num: 47, name: "Launch-List", url: "https://www.launch-list.org", da: 47 },
  { num: 48, name: "StartupListing", url: "https://startuplist.ing", da: 42 },
  { num: 49, name: "ProductBurst", url: "https://productburst.com", da: 41 },
  { num: 50, name: "Million Dot Homepage", url: "https://milliondothomepage.com", da: 41 },
  { num: 51, name: "StartupBase", url: "https://startupbase.io", da: 39 },
  { num: 52, name: "AlternAI", url: "https://altern.ai", da: 39 },
  { num: 53, name: "Launch Vault", url: "https://www.launchvault.dev", da: 39 },
  { num: 54, name: "1000 Tools", url: "https://1000.tools", da: 38 },
  { num: 55, name: "Saaspa.ge", url: "https://www.saaspa.ge", da: 38 },
  { num: 56, name: "ShipSquad", url: "https://shipsquad.space", da: 38 },
  { num: 57, name: "Makerhunt", url: "https://makerhunt.io", da: 32 },
  { num: 58, name: "Bowora (previously: Best Of Web)", url: "https://bowora.com/?via=xrxo1fne&ref=linkto", da: 31 },
  { num: 59, name: "Awesome Indie", url: "https://awesomeindie.com", da: 30 },
  { num: 60, name: "Sidehunt", url: "https://sidehunt.io", da: 30 },
  { num: 61, name: "Toolhub", url: "https://toolhub.me", da: 28 },
  { num: 62, name: "Simple Lister", url: "https://simplelister.com", da: 28 },
  { num: 63, name: "AgentLocker", url: "https://www.agentlocker.ai", da: 27 },
  { num: 64, name: "JustGotFound", url: "https://justgotfound.com", da: 21 },
  { num: 65, name: "AI Directory", url: "https://aidirectory.wiki", da: 15 },
  { num: 66, name: "LaunchScroll", url: "https://launchscroll.com", da: 45 },
];

interface RawReddit {
  name: string;
  subcategory: string;
}

const rawRedditCommunities: RawReddit[] = [
  // General Marketing
  { name: "r/marketing", subcategory: "General Marketing" },
  { name: "r/digital_marketing", subcategory: "General Marketing" },
  { name: "r/MarketingResearch", subcategory: "General Marketing" },
  { name: "r/MarketingStrategy", subcategory: "General Marketing" },
  { name: "r/marketingautomation", subcategory: "General Marketing" },
  { name: "r/ContentMarketing", subcategory: "General Marketing" },
  { name: "r/Advertising", subcategory: "General Marketing" },
  { name: "r/PRpros", subcategory: "General Marketing" },
  { name: "r/InboundMarketing", subcategory: "General Marketing" },
  { name: "r/OutboundMarketing", subcategory: "General Marketing" },
  { name: "r/guerrillamarketing", subcategory: "General Marketing" },
  { name: "r/Branding", subcategory: "General Marketing" },
  { name: "r/MarketingTips", subcategory: "General Marketing" },
  { name: "r/MarketingIdeas", subcategory: "General Marketing" },
  { name: "r/MarketingPlan", subcategory: "General Marketing" },
  { name: "r/MarketingAdvice", subcategory: "General Marketing" },
  { name: "r/BrandManagement", subcategory: "General Marketing" },
  { name: "r/BrandStrategy", subcategory: "General Marketing" },
  { name: "r/StrategicMarketing", subcategory: "General Marketing" },
  { name: "r/Marketing101", subcategory: "General Marketing" },
  { name: "r/MarketingInsights", subcategory: "General Marketing" },
  { name: "r/MarketingCommunity", subcategory: "General Marketing" },
  // SEO & Growth
  { name: "r/SEO", subcategory: "SEO & Growth" },
  { name: "r/bigseo", subcategory: "SEO & Growth" },
  { name: "r/TechSEO", subcategory: "SEO & Growth" },
  { name: "r/SEOgrowth", subcategory: "SEO & Growth" },
  { name: "r/LocalSEO", subcategory: "SEO & Growth" },
  { name: "r/ecommerceSEO", subcategory: "SEO & Growth" },
  { name: "r/affiliate_marketing", subcategory: "SEO & Growth" },
  { name: "r/Affiliatemarketing", subcategory: "SEO & Growth" },
  { name: "r/NicheWebsites", subcategory: "SEO & Growth" },
  { name: "r/growthhacking", subcategory: "SEO & Growth" },
  { name: "r/GrowthHacking", subcategory: "SEO & Growth" },
  { name: "r/GrowthMarketing", subcategory: "SEO & Growth" },
  { name: "r/ProductMarketing", subcategory: "SEO & Growth" },
  { name: "r/ProductLedGrowth", subcategory: "SEO & Growth" },
  { name: "r/SEOcontent", subcategory: "SEO & Growth" },
  { name: "r/SEOTools", subcategory: "SEO & Growth" },
  { name: "r/LocalBusinessSEO", subcategory: "SEO & Growth" },
  { name: "r/SEOMarketing", subcategory: "SEO & Growth" },
  { name: "r/LinkBuilding", subcategory: "SEO & Growth" },
  { name: "r/SEOTechniques", subcategory: "SEO & Growth" },
  { name: "r/SearchEngineOptimization", subcategory: "SEO & Growth" },
  { name: "r/SEOHelp", subcategory: "SEO & Growth" },
  { name: "r/MarketingGrowth", subcategory: "SEO & Growth" },
  { name: "r/GrowthStrategy", subcategory: "SEO & Growth" },
  // Social Media Marketing
  { name: "r/socialmedia", subcategory: "Social Media Marketing" },
  { name: "r/SocialMediaMarketing", subcategory: "Social Media Marketing" },
  { name: "r/InstagramMarketing", subcategory: "Social Media Marketing" },
  { name: "r/FacebookAds", subcategory: "Social Media Marketing" },
  { name: "r/TikTokMarketing", subcategory: "Social Media Marketing" },
  { name: "r/Twitter", subcategory: "Social Media Marketing" },
  { name: "r/YouTubeMarketing", subcategory: "Social Media Marketing" },
  { name: "r/NewTubers", subcategory: "Social Media Marketing" },
  { name: "r/YouTube_startups", subcategory: "Social Media Marketing" },
  { name: "r/Creator", subcategory: "Social Media Marketing" },
  { name: "r/InfluencerMarketing", subcategory: "Social Media Marketing" },
  { name: "r/TikTokGrowth", subcategory: "Social Media Marketing" },
  { name: "r/SmallYTChannel", subcategory: "Social Media Marketing" },
  { name: "r/ContentCreators", subcategory: "Social Media Marketing" },
  { name: "r/InstagramGrowth", subcategory: "Social Media Marketing" },
  { name: "r/InstagramForBusiness", subcategory: "Social Media Marketing" },
  { name: "r/LinkedInMarketing", subcategory: "Social Media Marketing" },
  { name: "r/SnapchatMarketing", subcategory: "Social Media Marketing" },
  { name: "r/RedditMarketing", subcategory: "Social Media Marketing" },
  { name: "r/PinterestMarketing", subcategory: "Social Media Marketing" },
  { name: "r/SocialMediaGrowth", subcategory: "Social Media Marketing" },
  { name: "r/CreatorEconomy", subcategory: "Social Media Marketing" },
  { name: "r/TwitterMarketing", subcategory: "Social Media Marketing" },
  { name: "r/TikTokForBusiness", subcategory: "Social Media Marketing" },
  // Paid Ads
  { name: "r/PPC", subcategory: "Paid Ads" },
  { name: "r/FacebookAdvertising", subcategory: "Paid Ads" },
  { name: "r/googleads", subcategory: "Paid Ads" },
  { name: "r/Adwords", subcategory: "Paid Ads" },
  { name: "r/GoogleAdsense", subcategory: "Paid Ads" },
  { name: "r/programmatic", subcategory: "Paid Ads" },
  { name: "r/MediaBuying", subcategory: "Paid Ads" },
  { name: "r/ConversionRateOptimization", subcategory: "Paid Ads" },
  { name: "r/landingpage", subcategory: "Paid Ads" },
  { name: "r/SalesFunnels", subcategory: "Paid Ads" },
  { name: "r/ClickFunnels", subcategory: "Paid Ads" },
  { name: "r/AdTech", subcategory: "Paid Ads" },
  { name: "r/ProgrammaticAdvertising", subcategory: "Paid Ads" },
  { name: "r/FacebookAdTips", subcategory: "Paid Ads" },
  { name: "r/AdOptimization", subcategory: "Paid Ads" },
  { name: "r/AdCampaigns", subcategory: "Paid Ads" },
  { name: "r/CPAmarketing", subcategory: "Paid Ads" },
  { name: "r/DisplayAdvertising", subcategory: "Paid Ads" },
  { name: "r/Retargeting", subcategory: "Paid Ads" },
  { name: "r/AdAnalytics", subcategory: "Paid Ads" },
  { name: "r/MarketingFunnel", subcategory: "Paid Ads" },
  // Copywriting / Content
  { name: "r/copywriting", subcategory: "Copywriting / Content" },
  { name: "r/copy", subcategory: "Copywriting / Content" },
  { name: "r/salescopy", subcategory: "Copywriting / Content" },
  { name: "r/emailmarketing", subcategory: "Copywriting / Content" },
  { name: "r/blogging", subcategory: "Copywriting / Content" },
  { name: "r/writingforbusiness", subcategory: "Copywriting / Content" },
  { name: "r/ContentMarketing", subcategory: "Copywriting / Content" },
  { name: "r/Storytelling", subcategory: "Copywriting / Content" },
  { name: "r/Copywriters", subcategory: "Copywriting / Content" },
  { name: "r/ContentStrategy", subcategory: "Copywriting / Content" },
  { name: "r/ContentCreation", subcategory: "Copywriting / Content" },
  { name: "r/CopywritingTips", subcategory: "Copywriting / Content" },
  { name: "r/SalesCopywriting", subcategory: "Copywriting / Content" },
  { name: "r/ContentWriters", subcategory: "Copywriting / Content" },
  { name: "r/ContentIdeas", subcategory: "Copywriting / Content" },
  { name: "r/BloggingTips", subcategory: "Copywriting / Content" },
  { name: "r/CreativeWritingMarketing", subcategory: "Copywriting / Content" },
  { name: "r/EmailCopy", subcategory: "Copywriting / Content" },
  { name: "r/MarketingCopy", subcategory: "Copywriting / Content" },
  { name: "r/ContentMarketingStrategy", subcategory: "Copywriting / Content" },
  // SaaS / Startup
  { name: "r/startups", subcategory: "SaaS / Startup" },
  { name: "r/startupgrowth", subcategory: "SaaS / Startup" },
  { name: "r/Entrepreneur", subcategory: "SaaS / Startup" },
  { name: "r/EntrepreneurRideAlong", subcategory: "SaaS / Startup" },
  { name: "r/SideProject", subcategory: "SaaS / Startup" },
  { name: "r/IndieHackers", subcategory: "SaaS / Startup" },
  { name: "r/startup_ideas", subcategory: "SaaS / Startup" },
  { name: "r/onlinebusiness", subcategory: "SaaS / Startup" },
  { name: "r/smallbusiness", subcategory: "SaaS / Startup" },
  { name: "r/SaaS", subcategory: "SaaS / Startup" },
  // E-commerce & Product
  { name: "r/ecommerce", subcategory: "E-commerce & Product" },
  { name: "r/shopify", subcategory: "E-commerce & Product" },
  { name: "r/AmazonSeller", subcategory: "E-commerce & Product" },
  { name: "r/dropshipping", subcategory: "E-commerce & Product" },
  { name: "r/EtsySellers", subcategory: "E-commerce & Product" },
  { name: "r/EcommerceMarketing", subcategory: "E-commerce & Product" },
  { name: "r/ecommercegrowth", subcategory: "E-commerce & Product" },
  { name: "r/EcomStartups", subcategory: "E-commerce & Product" },
  { name: "r/ProductMarketing", subcategory: "E-commerce & Product" },
  { name: "r/D2C", subcategory: "E-commerce & Product" },
  { name: "r/eCommerceBusiness", subcategory: "E-commerce & Product" },
  { name: "r/eCommerceGrowthHacks", subcategory: "E-commerce & Product" },
  { name: "r/ShopifyApps", subcategory: "E-commerce & Product" },
  { name: "r/AmazonFBA", subcategory: "E-commerce & Product" },
  { name: "r/DropshippingBusiness", subcategory: "E-commerce & Product" },
  { name: "r/DTCmarketing", subcategory: "E-commerce & Product" },
  { name: "r/EtsyMarketing", subcategory: "E-commerce & Product" },
  { name: "r/ProductLaunch", subcategory: "E-commerce & Product" },
  { name: "r/OnlineSMarketing", subcategory: "E-commerce & Product" },
  { name: "r/ShopifyMarketing", subcategory: "E-commerce & Product" },
  // Psychology / Consumer Behaviour
  { name: "r/ConsumerPsychology", subcategory: "Psychology / Consumer Behaviour" },
  { name: "r/BehavioralEconomics", subcategory: "Psychology / Consumer Behaviour" },
  { name: "r/neuromarketing", subcategory: "Psychology / Consumer Behaviour" },
  { name: "r/PsychologyOfMarketing", subcategory: "Psychology / Consumer Behaviour" },
  { name: "r/MarketingPsychology", subcategory: "Psychology / Consumer Behaviour" },
  { name: "r/BrandPsychology", subcategory: "Psychology / Consumer Behaviour" },
  // Niche / Hidden Gems
  { name: "r/TrafficGeneration", subcategory: "Niche / Hidden Gems" },
  { name: "r/OnlineMarketingTips", subcategory: "Niche / Hidden Gems" },
  { name: "r/AskMarketing", subcategory: "Niche / Hidden Gems" },
  { name: "r/StartupMarketing", subcategory: "Niche / Hidden Gems" },
  { name: "r/IndieBiz", subcategory: "Niche / Hidden Gems" },
  { name: "r/MarketingCaseStudies", subcategory: "Niche / Hidden Gems" },
  { name: "r/MarketingFails", subcategory: "Niche / Hidden Gems" },
  { name: "r/GrowthHacks", subcategory: "Niche / Hidden Gems" },
  { name: "r/MarketingAnalytics", subcategory: "Niche / Hidden Gems" },
  { name: "r/EmailMarketingTips", subcategory: "Niche / Hidden Gems" },
  { name: "r/MarketingTools", subcategory: "Niche / Hidden Gems" },
  { name: "r/DigitalMarketingTools", subcategory: "Niche / Hidden Gems" },
  { name: "r/InfluencerGrowth", subcategory: "Niche / Hidden Gems" },
  { name: "r/SmallBusinessMarketing", subcategory: "Niche / Hidden Gems" },
];

export const redditCommunities: Directory[] = rawRedditCommunities.map((r, i) => ({
  id: "reddit-" + (i + 1),
  num: i + 1,
  name: r.name,
  url: "https://reddit.com/" + r.name,
  da: null,
  dr: null,
  type: "free" as DirectoryType,
  dofollow: false,
  notes: null,
  category: "reddit" as DirectoryCategory,
  subcategory: r.subcategory,
}));

export const allDirectories: Directory[] = [
  ...transform(rawSaasDirectories, "saas", "directory"),
  ...transform(rawLaunchSites, "launch", "launch"),
];

// kept for any code still referencing these
export const saasDirectories = allDirectories.filter(d => d.category === "directory");
export const launchSites = allDirectories.filter(d => d.category === "launch");
